name: Temp Docflow Dispatch
on:
  workflow_dispatch:
    inputs:
      code:
        required: true
        type: string
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok > /tmp/ok
